// Header file for Arduino 
// PMDGEventDataServer
//

#define MOUSE_FLAG_RIGHTSINGLE -1
#define MOUSE_FLAG_MIDDLESINGLE -2
#define MOUSE_FLAG_LEFTSINGLE -3
#define MOUSE_FLAG_RIGHTDOUBLE -4
#define MOUSE_FLAG_MIDDLEDOUBLE -5
#define MOUSE_FLAG_LEFTDOUBLE -6
#define MOUSE_FLAG_RIGHTDRAG -7
#define MOUSE_FLAG_MIDDLEDRAG -8
#define MOUSE_FLAG_LEFTDRAG -9
#define MOUSE_FLAG_MOVE -10
#define MOUSE_FLAG_DOWN_REPEAT -11
#define MOUSE_FLAG_RIGHTRELEASE -12
#define MOUSE_FLAG_MIDDLERELEASE -13
#define MOUSE_FLAG_LEFTRELEASE -14
#define MOUSE_FLAG_WHEEL_FLIP -15
#define MOUSE_FLAG_WHEEL_SKIP -16
#define MOUSE_FLAG_WHEEL_UP -17
#define MOUSE_FLAG_WHEEL_DOWN -18
#define THIRD_PARTY_EVENT_ID_MIN -19
