// Header file for Arduino 
// PMDGEventDataServer
//
#define EVT_MCP_COURSE_SELECTOR_L 501
#define EVT_MCP_FD_SWITCH_L 502
#define EVT_MCP_AT_ARM_SWITCH 503
#define EVT_MCP_N1_SWITCH 504
#define EVT_MCP_SPEED_SWITCH 505
#define EVT_MCP_CO_SWITCH 506
#define EVT_MCP_SPEED_SELECTOR 507
#define EVT_MCP_VNAV_SWITCH 508
#define EVT_MCP_SPD_INTV_SWITCH 509
#define EVT_MCP_BANK_ANGLE_SELECTOR 510
#define EVT_MCP_HEADING_SELECTOR 511
#define EVT_MCP_LVL_CHG_SWITCH 512
#define EVT_MCP_HDG_SEL_SWITCH 513
#define EVT_MCP_APP_SWITCH 514
#define EVT_MCP_ALT_HOLD_SWITCH 515
#define EVT_MCP_VS_SWITCH 516
#define EVT_MCP_VOR_LOC_SWITCH 517
#define EVT_MCP_LNAV_SWITCH 518
#define EVT_MCP_ALTITUDE_SELECTOR 519
#define EVT_MCP_VS_SELECTOR 520
#define EVT_MCP_CMD_A_SWITCH 521
#define EVT_MCP_CMD_B_SWITCH 522
#define EVT_MCP_CWS_A_SWITCH 523
#define EVT_MCP_CWS_B_SWITCH 524
#define EVT_MCP_DISENGAGE_BAR 525
#define EVT_MCP_FD_SWITCH_R 526
#define EVT_MCP_COURSE_SELECTOR_R 527
#define EVT_MCP_ALT_INTV_SWITCH 528

